-- Clubes do sistema (escudos self-hosted em /logos/**), agrupados por liga.
-- GERADO por scripts/generate-seed.ts a partir de logos/manifest.json — revisado à mão.
-- badge_url é caminho RELATIVO; a API prefixa com reidopitaco.assets.base-url na leitura.
-- Cores aproximadas dos mantos/escudos (ajustáveis). Siglas sem pretensão de código oficial.
--
-- Idempotente (padrão da V22): só insere se não houver time do sistema ativo com o mesmo nome.
INSERT INTO teams
    (public_id, name, short_name, badge_url, primary_color, secondary_color, country_code, league_slug, league_name, is_system, team_type, active, created_at, updated_at)
SELECT
    gen_random_uuid(), v.name, v.short_name, v.badge_url, v.primary_color, v.secondary_color, v.country_code, v.league_slug, v.league_name,
    TRUE, 'CLUB', TRUE, now(), now()
FROM (VALUES
    -- Brasileirão Série A (br)
    ('Athletico Paranaense', 'CAP', '/logos/brazil/athletico-paranaense.png', '#C8102E', '#000000', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Atlético Mineiro', 'CAM', '/logos/brazil/atletico-mineiro.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Bahia', 'BAH', '/logos/brazil/bahia.png', '#006CB5', '#ED3237', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Remo', 'REM', '/logos/brazil/clube-do-remo.png', '#00278B', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Botafogo', 'BOT', '/logos/brazil/botafogo.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Chapecoense', 'CHA', '/logos/brazil/chapecoense.png', '#009846', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Corinthians', 'COR', '/logos/brazil/corinthians.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Coritiba', 'CTB', '/logos/brazil/coritiba.png', '#00544E', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Cruzeiro', 'CRU', '/logos/brazil/cruzeiro.png', '#003399', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Flamengo', 'FLA', '/logos/brazil/flamengo.png', '#E30613', '#000000', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Fluminense', 'FLU', '/logos/brazil/fluminense.png', '#7A0C2E', '#00613C', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Grêmio', 'GRE', '/logos/brazil/gremio.png', '#0D80BF', '#000000', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Internacional', 'INT', '/logos/brazil/internacional.png', '#E5050F', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Mirassol', 'MIR', '/logos/brazil/mirassol.png', '#FFD100', '#00693C', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Palmeiras', 'PAL', '/logos/brazil/palmeiras.png', '#006437', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('RB Bragantino', 'RBB', '/logos/brazil/rb-bragantino.png', '#FFFFFF', '#E00034', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('São Paulo', 'SAO', '/logos/brazil/sao-paulo.png', '#FE0000', '#000000', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Santos', 'SAN', '/logos/brazil/santos.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Vasco da Gama', 'VAS', '/logos/brazil/vasco-da-gama.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    ('Vitória', 'VIT', '/logos/brazil/vitoria.png', '#FF0000', '#000000', 'br', 'brasileirao-serie-a', 'Brasileirão Série A'),
    -- Brasileirão Série B (br)
    ('América Mineiro', 'AME', '/logos/brazil/america-mineiro.png', '#007A33', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Athletic-MG', 'ATH', '/logos/brazil/athletic.png', '#DA291C', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Atlético Goianiense', 'ACG', '/logos/brazil/atletico-goianiense.png', '#DC1E28', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Avaí', 'AVA', '/logos/brazil/avai.png', '#00679A', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Botafogo-SP', 'BSP', '/logos/brazil/botafogo-sp.png', '#DA291C', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Ceará', 'CEA', '/logos/brazil/ceara.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('CRB', 'CRB', '/logos/brazil/crb.png', '#DA291C', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Criciúma', 'CRI', '/logos/brazil/criciuma.png', '#FFD700', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Cuiabá', 'CUI', '/logos/brazil/cuiaba.png', '#FDB913', '#00613C', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Fortaleza', 'FOR', '/logos/brazil/fortaleza.png', '#006CB5', '#DA291C', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Goiás', 'GOI', '/logos/brazil/goias.png', '#00693C', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Londrina', 'LON', '/logos/brazil/londrina.png', '#0047AB', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Juventude', 'JUV', '/logos/brazil/juventude.png', '#009846', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Náutico', 'NAU', '/logos/brazil/nautico.png', '#DA291C', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Novorizontino', 'NOV', '/logos/brazil/novorizontino.png', '#FFD100', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Operário Ferroviário', 'OPE', '/logos/brazil/operario-ferroviario.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Ponte Preta', 'PON', '/logos/brazil/ponte-preta.png', '#000000', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('São Bernardo', 'SAO', '/logos/brazil/sao-bernardo.png', '#FFD100', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Sport Recife', 'SPT', '/logos/brazil/sport-recife.png', '#DA291C', '#000000', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    ('Vila Nova', 'VIL', '/logos/brazil/vila-nova.png', '#DA291C', '#FFFFFF', 'br', 'brasileirao-serie-b', 'Brasileirão Série B'),
    -- Premier League (gb-eng)
    ('Arsenal', 'ARS', '/logos/england/arsenal.png', '#EF0107', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Aston Villa', 'AVL', '/logos/england/aston-villa.png', '#670E36', '#95BFE5', 'gb-eng', 'premier-league', 'Premier League'),
    ('Chelsea', 'CHE', '/logos/england/chelsea.png', '#034694', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Everton', 'EVE', '/logos/england/everton.png', '#003399', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Liverpool', 'LIV', '/logos/england/liverpool.png', '#C8102E', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Manchester City', 'MCI', '/logos/england/manchester-city.png', '#6CABDD', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Manchester United', 'MUN', '/logos/england/manchester-united.png', '#DA291C', '#000000', 'gb-eng', 'premier-league', 'Premier League'),
    ('Newcastle', 'NEW', '/logos/england/newcastle.png', '#241F20', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Tottenham', 'TOT', '/logos/england/tottenham.png', '#FFFFFF', '#132257', 'gb-eng', 'premier-league', 'Premier League'),
    ('Bournemouth', 'BOU', '/logos/england/bournemouth.png', '#DA291C', '#000000', 'gb-eng', 'premier-league', 'Premier League'),
    ('Brentford', 'BRE', '/logos/england/brentford.png', '#E30613', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Brighton', 'BHA', '/logos/england/brighton.png', '#0057B8', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Coventry City', 'COV', '/logos/england/coventry-city.png', '#78D2F2', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Crystal Palace', 'CRY', '/logos/england/crystal-palace.png', '#1B458F', '#C4122E', 'gb-eng', 'premier-league', 'Premier League'),
    ('Fulham', 'FUL', '/logos/england/fulham.png', '#FFFFFF', '#000000', 'gb-eng', 'premier-league', 'Premier League'),
    ('Hull City', 'HUL', '/logos/england/hull-city.png', '#F5971D', '#000000', 'gb-eng', 'premier-league', 'Premier League'),
    ('Ipswich', 'IPS', '/logos/england/ipswich.png', '#0044A9', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Leeds United', 'LEE', '/logos/england/leeds-united.png', '#FFFFFF', '#1D428A', 'gb-eng', 'premier-league', 'Premier League'),
    ('Nottingham Forest', 'NFO', '/logos/england/nottingham-forest.png', '#DD0000', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    ('Sunderland', 'SUN', '/logos/england/sunderland.png', '#EB172B', '#FFFFFF', 'gb-eng', 'premier-league', 'Premier League'),
    -- La Liga (es)
    ('Barcelona', 'BAR', '/logos/spain/barcelona.png', '#A50044', '#004D98', 'es', 'la-liga', 'La Liga'),
    ('Real Madrid', 'RMA', '/logos/spain/real-madrid.png', '#FFFFFF', '#FEBE10', 'es', 'la-liga', 'La Liga'),
    ('Atlético de Madrid', 'ATM', '/logos/spain/atletico-madrid.png', '#CB3524', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Sevilla', 'SEV', '/logos/spain/sevilla.png', '#FFFFFF', '#D8171E', 'es', 'la-liga', 'La Liga'),
    ('Valencia', 'VAL', '/logos/spain/valencia.png', '#FFFFFF', '#EE3524', 'es', 'la-liga', 'La Liga'),
    ('Villarreal', 'VIL', '/logos/spain/villarreal.png', '#FFE667', '#005187', 'es', 'la-liga', 'La Liga'),
    ('Real Betis', 'BET', '/logos/spain/real-betis.png', '#00954C', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Real Sociedad', 'RSO', '/logos/spain/real-sociedad.png', '#0067B1', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Athletic Bilbao', 'ATH', '/logos/spain/athletic-club.png', '#EE2523', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Espanyol', 'ESP', '/logos/spain/espanyol.png', '#007FC8', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Celta de Vigo', 'CEL', '/logos/spain/celta.png', '#8AC3EE', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Deportivo Alavés', 'ALA', '/logos/spain/deportivo.png', '#0761AF', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Deportivo La Coruña', 'DEP', '/logos/spain/deportivo-la-coruna.png', '#005CA5', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Elche', 'ELC', '/logos/spain/elche.png', '#00A650', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Getafe', 'GET', '/logos/spain/getafe.png', '#005999', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Levante', 'LEV', '/logos/spain/levante.png', '#B4053F', '#005999', 'es', 'la-liga', 'La Liga'),
    ('Málaga', 'MAL', '/logos/spain/malaga.png', '#0072BC', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Osasuna', 'OSA', '/logos/spain/osasuna.png', '#D91A21', '#0A346F', 'es', 'la-liga', 'La Liga'),
    ('Racing Santander', 'RAC', '/logos/spain/racing.png', '#00A651', '#FFFFFF', 'es', 'la-liga', 'La Liga'),
    ('Rayo Vallecano', 'RAY', '/logos/spain/rayo-vallecano.png', '#FFFFFF', '#E53027', 'es', 'la-liga', 'La Liga'),
    -- Serie A (it)
    ('Juventus', 'JUV', '/logos/italy/juventus.png', '#000000', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Milan', 'MIL', '/logos/italy/milan.png', '#FB090B', '#000000', 'it', 'serie-a', 'Serie A'),
    ('Inter', 'INT', '/logos/italy/inter.png', '#0068A8', '#000000', 'it', 'serie-a', 'Serie A'),
    ('Napoli', 'NAP', '/logos/italy/napoli.png', '#12A0D7', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Roma', 'ROM', '/logos/italy/roma.png', '#8E1F2F', '#F0BC42', 'it', 'serie-a', 'Serie A'),
    ('Lazio', 'LAZ', '/logos/italy/lazio.png', '#87D8F7', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Fiorentina', 'FIO', '/logos/italy/fiorentina.png', '#482E92', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Atalanta', 'ATA', '/logos/italy/atalanta.png', '#1E71B8', '#000000', 'it', 'serie-a', 'Serie A'),
    ('Bologna', 'BOL', '/logos/italy/bologna.png', '#1A2F48', '#D4001F', 'it', 'serie-a', 'Serie A'),
    ('Cagliari', 'CAG', '/logos/italy/cagliari.png', '#B01028', '#002350', 'it', 'serie-a', 'Serie A'),
    ('Como 1907', 'COM', '/logos/italy/como-1907.png', '#00306B', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Frosinone Calcio', 'FRO', '/logos/italy/frosinone.png', '#FFD700', '#005CA9', 'it', 'serie-a', 'Serie A'),
    ('Genoa', 'GEN', '/logos/italy/genoa.png', '#AE1919', '#00285E', 'it', 'serie-a', 'Serie A'),
    ('Lecce', 'LEC', '/logos/italy/lecce.png', '#FFD700', '#DA291C', 'it', 'serie-a', 'Serie A'),
    ('Monza', 'MON', '/logos/italy/monza.png', '#EE0E36', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Parma', 'PAR', '/logos/italy/parma.png', '#FFD700', '#034694', 'it', 'serie-a', 'Serie A'),
    ('Sassuolo', 'SAS', '/logos/italy/sassuolo.png', '#00A752', '#000000', 'it', 'serie-a', 'Serie A'),
    ('Torino', 'TOR', '/logos/italy/torino.png', '#8B1B23', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Udinese', 'UDI', '/logos/italy/udinese.png', '#000000', '#FFFFFF', 'it', 'serie-a', 'Serie A'),
    ('Venezia', 'VEN', '/logos/italy/venezia.png', '#000000', '#F58220', 'it', 'serie-a', 'Serie A'),
    -- Bundesliga (de)
    ('Bayern de Munique', 'BAY', '/logos/germany/bayern-munchen.png', '#DC052D', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Borussia Dortmund', 'BVB', '/logos/germany/borussia-dortmund.png', '#FDE100', '#000000', 'de', 'bundesliga', 'Bundesliga'),
    ('RB Leipzig', 'RBL', '/logos/germany/rb-leipzig.png', '#FFFFFF', '#DD0741', 'de', 'bundesliga', 'Bundesliga'),
    ('Bayer Leverkusen', 'B04', '/logos/germany/bayer-leverkusen.png', '#E32221', '#000000', 'de', 'bundesliga', 'Bundesliga'),
    ('Eintracht Frankfurt', 'SGE', '/logos/germany/eintracht-frankfurt.png', '#E1000F', '#000000', 'de', 'bundesliga', 'Bundesliga'),
    ('Union Berlin', 'UNI', '/logos/germany/union-berlin.png', '#EB1923', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Schalke 04', 'S04', '/logos/germany/schalke-04.png', '#004D9D', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Hamburger SV', 'HSV', '/logos/germany/hamburger-sv.png', '#FFFFFF', '#0A3F86', 'de', 'bundesliga', 'Bundesliga'),
    ('Augsburg', 'AUG', '/logos/germany/augsburg.png', '#BA3733', '#46714D', 'de', 'bundesliga', 'Bundesliga'),
    ('Werder Bremen', 'SVW', '/logos/germany/werder-bremen.png', '#1D9053', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Freiburg', 'SCF', '/logos/germany/freiburg.png', '#000000', '#DD0741', 'de', 'bundesliga', 'Bundesliga'),
    ('Hoffenheim', 'TSG', '/logos/germany/hoffenheim.png', '#1C63B7', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Colônia', 'KOE', '/logos/germany/koln.png', '#ED1C24', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Mainz 05', 'M05', '/logos/germany/mainz-05.png', '#C3141E', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('Borussia Mönchengladbach', 'BMG', '/logos/germany/borussia-monchengladbach.png', '#000000', '#00A651', 'de', 'bundesliga', 'Bundesliga'),
    ('SC Paderborn', 'PAD', '/logos/germany/paderborn.png', '#005CA9', '#000000', 'de', 'bundesliga', 'Bundesliga'),
    ('SV Elversberg', 'ELV', '/logos/germany/sv-elversberg.png', '#005CA9', '#FFFFFF', 'de', 'bundesliga', 'Bundesliga'),
    ('VfB Stuttgart', 'VFB', '/logos/germany/vfb-stuttgart.png', '#FFFFFF', '#E32219', 'de', 'bundesliga', 'Bundesliga'),
    -- Ligue 1 (fr)
    ('Paris Saint-Germain', 'PSG', '/logos/france/paris-saint-germain.png', '#004170', '#DA291C', 'fr', 'ligue-1', 'Ligue 1'),
    ('Angers', 'ANG', '/logos/france/angers.png', '#000000', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Auxerre', 'AUX', '/logos/france/auxerre.png', '#FFFFFF', '#003C7E', 'fr', 'ligue-1', 'Ligue 1'),
    ('Brest', 'BRE', '/logos/france/brest.png', '#E30613', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Le Havre AC', 'LEH', '/logos/france/le-havre-ac.png', '#75AADB', '#0D1F41', 'fr', 'ligue-1', 'Ligue 1'),
    ('RC Lens', 'RCL', '/logos/france/rc-lens.png', '#FFD700', '#EC1C24', 'fr', 'ligue-1', 'Ligue 1'),
    ('Le Mans FC', 'LEM', '/logos/france/le-mans.png', '#FFD100', '#B01028', 'fr', 'ligue-1', 'Ligue 1'),
    ('Lille', 'LIL', '/logos/france/lille.png', '#E01E13', '#000E42', 'fr', 'ligue-1', 'Ligue 1'),
    ('Lorient FC', 'LOR', '/logos/france/lorient.png', '#F36F21', '#000000', 'fr', 'ligue-1', 'Ligue 1'),
    ('Lyon', 'LYO', '/logos/france/lyon.png', '#FFFFFF', '#DA001A', 'fr', 'ligue-1', 'Ligue 1'),
    ('Marseille', 'MAR', '/logos/france/marseille.png', '#FFFFFF', '#2FAEE0', 'fr', 'ligue-1', 'Ligue 1'),
    ('AS Monaco', 'ASM', '/logos/france/as-monaco.png', '#ED1C24', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Nice', 'NIC', '/logos/france/nice.png', '#ED1C24', '#000000', 'fr', 'ligue-1', 'Ligue 1'),
    ('Paris FC', 'PFC', '/logos/france/paris-fc.png', '#00337F', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Rennes', 'REN', '/logos/france/rennes.png', '#E13327', '#000000', 'fr', 'ligue-1', 'Ligue 1'),
    ('RC Strasbourg Alsace', 'STR', '/logos/france/rc-strasbourg-alsace.png', '#009FE3', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Toulouse', 'TOU', '/logos/france/toulouse.png', '#615395', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    ('Troyes', 'TRO', '/logos/france/troyes.png', '#005CA9', '#FFFFFF', 'fr', 'ligue-1', 'Ligue 1'),
    -- Primeira Liga (pt)
    ('Sporting CP', 'SCP', '/logos/portugal/sporting-cp.png', '#008057', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Benfica', 'SLB', '/logos/portugal/benfica.png', '#E20E17', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('FC Porto', 'FCP', '/logos/portugal/fc-porto.png', '#00428C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Académico de Viseu', 'ACA', '/logos/portugal/academico-de-viseu.png', '#00693C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Alverca', 'ALV', '/logos/portugal/alverca.png', '#DA291C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Arouca', 'ARO', '/logos/portugal/arouca.png', '#FFD700', '#00306B', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Casa Pia AC', 'CAS', '/logos/portugal/casa-pia-ac.png', '#000000', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Estrela da Amadora', 'EST', '/logos/portugal/estrela-da-amadora.png', '#DA291C', '#009846', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Estoril', 'EST', '/logos/portugal/estoril.png', '#FFD700', '#00306B', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Famalicão', 'FAM', '/logos/portugal/famalicao.png', '#00306B', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Gil Vicente', 'GIL', '/logos/portugal/gil-vicente.png', '#DA291C', '#00306B', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Marítimo', 'MAR', '/logos/portugal/maritimo.png', '#009846', '#DA291C', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Moreirense', 'MOR', '/logos/portugal/moreirense.png', '#00693C', '#FFD700', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Nacional da Madeira', 'NAC', '/logos/portugal/nacional-da-madeira.png', '#000000', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Rio Ave', 'RIO', '/logos/portugal/rio-ave.png', '#00693C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Santa Clara', 'SAN', '/logos/portugal/santa-clara.png', '#DA291C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('SC Braga', 'SCB', '/logos/portugal/sc-braga.png', '#DA291C', '#FFFFFF', 'pt', 'primeira-liga', 'Primeira Liga'),
    ('Vitória de Guimarães', 'VSC', '/logos/portugal/vitoria-de-guimaraes.png', '#FFFFFF', '#000000', 'pt', 'primeira-liga', 'Primeira Liga'),
    -- Eredivisie (nl)
    ('PSV Eindhoven', 'PSV', '/logos/netherlands/psv.png', '#ED1C24', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('Ajax', 'AJA', '/logos/netherlands/ajax.png', '#D2122E', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('Feyenoord', 'FEY', '/logos/netherlands/feyenoord.png', '#E01E28', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('FC Utrecht', 'UTR', '/logos/netherlands/fc-utrecht.png', '#DA291C', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('AZ Alkmaar', 'AZ', '/logos/netherlands/az-alkmaar.png', '#DA291C', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('Twente', 'TWE', '/logos/netherlands/twente.png', '#DA291C', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('ADO Den Haag', 'ADO', '/logos/netherlands/ado-den-haag.png', '#009846', '#FFD700', 'nl', 'eredivisie', 'Eredivisie'),
    ('Excelsior Rotterdam', 'EXC', '/logos/netherlands/excelsior-rotterdam.png', '#000000', '#DA291C', 'nl', 'eredivisie', 'Eredivisie'),
    ('Telstar', 'TEL', '/logos/netherlands/telstar.png', '#FFFFFF', '#000000', 'nl', 'eredivisie', 'Eredivisie'),
    ('Fortuna Sittard', 'FOR', '/logos/netherlands/fortuna-sittard.png', '#FFD700', '#009846', 'nl', 'eredivisie', 'Eredivisie'),
    ('Go Ahead Eagles', 'GAE', '/logos/netherlands/go-ahead-eagles.png', '#DA291C', '#FFD700', 'nl', 'eredivisie', 'Eredivisie'),
    ('FC Groningen', 'GRO', '/logos/netherlands/fc-groningen.png', '#009846', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('SC Heerenveen', 'HEE', '/logos/netherlands/sc-heerenveen.png', '#004FA3', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('NEC Nijmegen', 'NEC', '/logos/netherlands/nec-nijmegen.png', '#DA291C', '#009846', 'nl', 'eredivisie', 'Eredivisie'),
    ('Sparta Rotterdam', 'SPA', '/logos/netherlands/sparta-rotterdam.png', '#DA291C', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('Willem II', 'WIL', '/logos/netherlands/willem-ii.png', '#DA291C', '#003C7E', 'nl', 'eredivisie', 'Eredivisie'),
    ('PEC Zwolle', 'PEC', '/logos/netherlands/pec-zwolle.png', '#004FA3', '#FFFFFF', 'nl', 'eredivisie', 'Eredivisie'),
    ('SC Cambuur', 'CAM', '/logos/netherlands/sc-cambuur.png', '#FFD700', '#00306B', 'nl', 'eredivisie', 'Eredivisie'),
    -- Primera División (ar)
    ('Aldosivi', 'ALD', '/logos/argentina/aldosivi.png', '#FFD700', '#009846', 'ar', 'primera-division-arg', 'Primera División'),
    ('Argentinos Juniors', 'ARG', '/logos/argentina/argeninos-juniors.png', '#DA291C', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Atlético Tucumán', 'ATL', '/logos/argentina/atletico-tucuman.png', '#75AADB', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Banfield', 'BAN', '/logos/argentina/banfield.png', '#009846', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Barracas Central', 'BAR', '/logos/argentina/barracas-central.png', '#DA291C', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Belgrano', 'BEL', '/logos/argentina/belgrano.png', '#75AADB', '#000000', 'ar', 'primera-division-arg', 'Primera División'),
    ('Boca Juniors', 'BOC', '/logos/argentina/boca-juniors.png', '#003B94', '#FDB913', 'ar', 'primera-division-arg', 'Primera División'),
    ('Huracán', 'HUR', '/logos/argentina/ca-huracan.png', '#FFFFFF', '#DA291C', 'ar', 'primera-division-arg', 'Primera División'),
    ('Central Córdoba', 'CEN', '/logos/argentina/central-cordoba.png', '#000000', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Platense', 'PLA', '/logos/argentina/club-atletico-platanense.png', '#8B4513', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Defensa y Justicia', 'DEF', '/logos/argentina/defensa-y-justicia.png', '#FFD700', '#009846', 'ar', 'primera-division-arg', 'Primera División'),
    ('Deportivo Riestra', 'DEP', '/logos/argentina/deportivo-riestra.png', '#000000', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Estudiantes de La Plata', 'EST', '/logos/argentina/estudiantes-de-la-plata.png', '#DA291C', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Gimnasia La Plata', 'GIM', '/logos/argentina/gimnasia-lp.png', '#FFFFFF', '#00306B', 'ar', 'primera-division-arg', 'Primera División'),
    ('Independiente', 'IND', '/logos/argentina/independiente.png', '#E10613', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Independiente Rivadavia', 'IND', '/logos/argentina/independiente-rivadavia.png', '#00306B', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Instituto Córdoba', 'INS', '/logos/argentina/instituto-cordoba.png', '#DA291C', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Lanús', 'LAN', '/logos/argentina/lanus.png', '#800000', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Newell''s Old Boys', 'NOB', '/logos/argentina/newells-old-boys.png', '#DA291C', '#000000', 'ar', 'primera-division-arg', 'Primera División'),
    ('Racing Club', 'RAC', '/logos/argentina/racing-club.png', '#75AADB', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('River Plate', 'RIV', '/logos/argentina/river-plate.png', '#FFFFFF', '#EB192D', 'ar', 'primera-division-arg', 'Primera División'),
    ('Rosario Central', 'ROS', '/logos/argentina/rosario-central.png', '#FDB913', '#00306B', 'ar', 'primera-division-arg', 'Primera División'),
    ('San Lorenzo de Almagro', 'SLO', '/logos/argentina/san-lorenzo-de-almagro.png', '#00306B', '#DA291C', 'ar', 'primera-division-arg', 'Primera División'),
    ('Sarmiento', 'SAR', '/logos/argentina/sarmiento.png', '#009846', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Talleres', 'TAL', '/logos/argentina/talleres.png', '#00306B', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Tigre', 'TIG', '/logos/argentina/tigre.png', '#00306B', '#DA291C', 'ar', 'primera-division-arg', 'Primera División'),
    ('Unión de Santa Fe', 'UNI', '/logos/argentina/union.png', '#DA291C', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División'),
    ('Vélez Sarsfield', 'VEL', '/logos/argentina/velez-sarsfield.png', '#FFFFFF', '#00306B', 'ar', 'primera-division-arg', 'Primera División'),
    ('Gimnasia y Esgrima de Mendoza', 'GIM', '/logos/argentina/gimnasia-y-esgrima.png', '#FFFFFF', '#000000', 'ar', 'primera-division-arg', 'Primera División'),
    ('Estudiantes de Río Cuarto', 'EST', '/logos/argentina/estudiantes-de-rio-cuarto.png', '#75AADB', '#FFFFFF', 'ar', 'primera-division-arg', 'Primera División')
) AS v(name, short_name, badge_url, primary_color, secondary_color, country_code, league_slug, league_name)
WHERE NOT EXISTS (
    SELECT 1 FROM teams t
    WHERE t.is_system = TRUE AND t.active = TRUE
      AND LOWER(t.name) = LOWER(v.name)
);
